name: Latest Release Build
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Firefox Manifest v2 Version
        run: |
          cd firefox-mv2
          apt install jq
          VERSION=$(echo -n "${{ github.ref }}" | sed 's/[refs\/tagv]//g' | sed 's/-.*//') jq '.version = env.VERSION' package.json > package.json.tmp && mv package.json.tmp package.json
          yarn
          yarn update:list
          yarn build:production
          yarn package
      - name: Build Chrome Manifest v3 Version
        run: |
          cd chrome-mv3
          yarn
          yarn update:list
          VERSION=$(echo -n "${{ github.ref }}" | sed 's/[refs\/tagv]//g' | sed 's/-.*//') yarn build:chrome
          yarn package
      - name: Upload Chrome build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: chrome-mv3/dist/LiveTL-Chrome.zip
          asset_name: LiveTL-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Firefox build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: firefox-mv2/dist/LiveTL-Firefox.zip
          asset_name: LiveTL-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
