name: Latest Release Build

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to build and upload
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Build Firefox Manifest v2 Version
        run: |
          cd firefox-mv2
          sudo apt install jq
          VERSION=$(echo -n "$RELEASE_TAG" | sed 's/^v//g' | sed 's/-.*//')
          jq --arg version "$VERSION" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
          yarn
          yarn update:list
          yarn build:production
          yarn package

      - name: Build Chrome Manifest v3 Version
        run: |
          cd chrome-mv3
          yarn
          yarn update:list
          VERSION=$(echo -n "$RELEASE_TAG" | sed 's/^v//g' | sed 's/-.*//') yarn build:chrome
          yarn package

      - name: Upload Chrome build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: chrome-mv3/dist/LiveTL-Chrome.zip
          asset_name: LiveTL-Chrome.zip
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
      - name: Upload Firefox build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: firefox-mv2/dist/LiveTL-Firefox.zip
          asset_name: LiveTL-Firefox.zip
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
